### Successful login (Azure)
POST https://cst8919-lab2-rahaf-h3bhe3gpekggd8fk.canadacentral-01.azurewebsites.net/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=pass123

### Failed login (Azure)
POST https://cst8919-lab2-rahaf-h3bhe3gpekggd8fk.canadacentral-01.azurewebsites.net/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=wrongpass

### Another failed login (Azure)
POST https://cst8919-lab2-rahaf-h3bhe3gpekggd8fk.canadacentral-01.azurewebsites.net/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=123456
